// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omvknszvotyxgiqgknhv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tdmtuc3p2b3R5eGdpcWdrbmh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjQ2NDAsImV4cCI6MjA3MDAwMDY0MH0.xermbvUnjdEmxnuDFmCZTG7xoPqS49tXR7nDbXOXFbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});